{
    "name": "Custom Vendor SKU field",
    "version": "1.0",
    "description": "",
    "summary": "",
    "author": "",
    "website": "",
    "license": "LGPL-3",
    "category": "",
    "depends": ["purchase"],
    "data": ["views/purchase_view.xml"],
    "demo": [""],
    "auto_install": False,
    "application": False,
    "assets": {},
}
